layout_spectrum: 0.5336425
typography_spectrum: 0.4680225
color:
  saturation: 0.02326947
  lightness: 0.2123377
  brandStrength: 0.1035786
  rhythmicContrast: 0.6038032
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
name: Frank Bardon
