name: Frank Bardon
favicon: null
layout_spectrum: 0.98104
typography_spectrum: 0.39022
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dddddd'
    - '#7b8d99'
    - '#303847'
    - '#bc8c20'
    - '#e39a9d'
  brandStrength: 0.125
  lightness: 0.8125
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
